# Generated by Django 4.1.2 on 2023-10-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0079_alter_package_name_alter_package_namespace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="embedded_packages",
            field=models.ManyToManyField(
                help_text="Packages that are contained within this Package.",
                related_name="embedded_in",
                to="packagedb.package",
            ),
        ),
    ]
